addSbtPlugin("org.scala-js"        % "sbt-scalajs"  % "1.13.2")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat" % "0.5.0")
addSbtPlugin("io.indigoengine"     % "sbt-indigo"   % "0.15.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix" % "0.9.31")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"  % "0.3.1")
addSbtPlugin("com.github.sbt"      % "sbt-site"     % "1.5.0")
addSbtPlugin("com.github.sbt"      % "sbt-ghpages"  % "0.8.0")
